_core:
  default_config_hash: _jBWHDxcUqiULjXJMHx8WwoT1VIODfJ3jsHA7pycQos
connector: oauth
limit: 100
connector_config:
  scheme: ""
  base_url: ""
  port:
  path: ""
  username: ""
  password: ""
cache: "3600"
