name: mautic-app
recipe: lamp
config:
  webroot: docroot
  php: "8.2"
  database: mysql:5.7

tooling:
  mt:
    service: appserver
    description: Run Mautic commands
    cmd: php bin/console
  node:
    service: appserver
  npm:
    service: appserver
proxy:
  mailhog:
    - mail.mautic-contrib.lndo.site
services:
  mailhog:
    type: mailhog
    portforward: true
  appserver:
    type: php:8.2
    build_as_root:
      - docker-php-ext-install sockets
      - docker-php-ext-configure imap --with-kerberos --with-imap-ssl && docker-php-ext-install imap
      # Note that you will want to use the script for the major version of node you want to install
      # See: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
      - curl -sL https://deb.nodesource.com/setup_22.x | bash -
      - apt-get install -y nodejs
    xdebug: true
    config:
      php: .lando/php/php.ini
