plugin.plugin_configuration.mautic_paragraph_connector.basic_auth:
  type: plugin.plugin_configuration.mautic_paragraph.standard
  label: 'Mautic basic authentication connector settings'
  mapping:
    username:
      type: string
      label: 'Username for HTTP basic authentication'
    password:
      type: string
      label: 'Password for HTTP basic authentication'

